# Docker Compose for development environment
version: '3.7'
services:
  # Mysql Database
  mysql:
    image: mysql:5.7.27
    container_name: mysql
    environment:
      MYSQL_DATABASE: appDevelopment
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: W1v2066D36757w
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"
    volumes:
      - appDB:/var/lib/mysql
  # Redis Database
  redis:
    image: redis:5.0.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
  # InfluxDB
  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxDB:/var/lib/influxdb
    networks:
      - influx-network
  # Chronograf
  chronograf:
    image: chronograf:1.7-alpine
    container_name: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "8888:8888"
    volumes:
      - chronograf:/var/lib/chronograf
    networks:
      - influx-network

# Docker Volumes
volumes:
  appDB:
  influxDB:
  chronograf:

networks:
  influx-network:
    driver: bridge
